import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContext } from "@/contexts/auth-context";
import { cookies } from "next/headers";
import { WorkspaceContext } from "@/contexts/workspace-context";
import { RequestContext } from "@/contexts/request-context";
import { ThemeProvider } from "next-themes";
import { SettingContext } from "@/contexts/setting-context";
import { ModalContext } from "@/contexts/modal-context";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const token = (await cookies()).get("note_jwt_token")?.value;

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider attribute={"class"} defaultTheme="light">
					<ModalContext>
						<AuthContext token={token}>
							<SettingContext token={token}>
								<WorkspaceContext token={token}>
									<RequestContext>{children}</RequestContext>
								</WorkspaceContext>
							</SettingContext>
						</AuthContext>
					</ModalContext>
				</ThemeProvider>
			</body>
		</html>
	);
}
